In [1]:
"""
Reference: https://www.youtube.com/watch?v=QIUxPv5PJOY&list=WL&index=267
To run test
"""
import math
import pandas_datareader.data as pdr
import numpy as np
import pandas as pd

from sklearn.preprocessing import MinMaxScaler
from keras.models import Sequential
from keras.layers import Dense, LSTM

import matplotlib.pyplot as plt

### Add for workaround of indice str->int issue
import yfinance as yf
yf.pdr_override()

In [2]:
df = pdr.get_data_yahoo('AAPL', start='2010-01-01', end='2020-12-31')
df

[*********************100%%**********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2010-01-04,7.622500,7.660714,7.585000,7.643214,6.487534,493729600
2010-01-05,7.664286,7.699643,7.616071,7.656429,6.498749,601904800
2010-01-06,7.656429,7.686786,7.526786,7.534643,6.395380,552160000
2010-01-07,7.562500,7.571429,7.466071,7.520714,6.383555,477131200
2010-01-08,7.510714,7.571429,7.466429,7.570714,6.425996,447610800
...,...,...,...,...,...,...
2020-12-23,132.160004,132.429993,130.779999,130.960007,128.856796,88223700
2020-12-24,131.320007,133.460007,131.100006,131.970001,129.850571,54930100
2020-12-28,133.990005,137.339996,133.509995,136.690002,134.494781,124486200
2020-12-29,138.050003,138.789993,134.339996,134.869995,132.703979,121047300
2020-12-30,135.580002,135.990005,133.399994,133.720001,131.572495,96452100